twig:
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/assets/images/': images
    form_themes:
        - 'bootstrap_5_layout.html.twig'
        - 'form/theme.html.twig'

when@test:
    twig:
        strict_variables: true
